server:  
  port: ${PORT:3333}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://172.31.87.243:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: false
    hostname: ${env.app.hostname}
    nonSecurePort: ${env.app.port}
    
ribbon:
  eureka:
    enabled: true