info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /accounts/**
      serviceId: account-service
    customer: 
      path: /customer/**
      serviceId: customer-service          

ribbon:
  eureka:
    enabled: true
  restclient:
    enabled: true  

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone:http://172.31.87.243:8761/eureka/
    registerWithEureka: true
  instance:
    prefer-ip-address: true
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG