node {

    withMaven(maven:'maven-3.6.2') {

        stage('Checkout') {
            git url: 'https://github.com/banibrata07/sample-spring-microservices.git', credentialsId: 'github-banibrataaws', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        
         stage('SSH transfer') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "${env.docker_host_discovery}",
             verbose: true,
             transfers: [
              sshTransfer(
               sourceFiles: "discovery-service/Dockerfile",
               removePrefix: "discovery-service",
               remoteDirectory: "//usr//discovery",
               execCommand: "docker ps -a"
              )
             ])
           ])
         }
        }


    }

}