node {

    withMaven(maven:'maven-3.6.2') {

        stage('Checkout') {
            git url: 'https://github.com/banibrata07/sample-spring-microservices.git', credentialsId: 'github-banibrataaws', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        
         stage('SSH transfer') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_discovery",
             verbose: true,
             transfers: [
              sshTransfer(
               sourceFiles: "discovery-service/Dockerfile",
               removePrefix: "discovery-service",
               remoteDirectory: "//usr//discovery",
               execCommand: "docker ps -a"
              )
               sshTransfer(
               sourceFiles: "discovery-service/target/discovery-service.jar",
               removePrefix: "discovery-service/target/",
               remoteDirectory: "//usr//discovery",
               execCommand: "docker stop discovery;docker rm -f discovery;docker image rm -f discovery;cd /usr/discovery;docker build -t discovery ."
              )
             ])
           ])
         }
        }


    }

}