spring:
  profile: peer1

server:  
  port: ${PORT:8761}
    
eureka:
  datacenter: cloud
  instance:
    hostname: 3.229.245.171
    prefer-ip-address: true
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://35.173.40.24:8761}/eureka
    registerWithEureka: true
    fetchRegistry: true
  server:
    enableSelfPreservation: true
    
    
--- 
spring:
  profile: peer2

server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: 35.173.40.24
    prefer-ip-address: true
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://3.229.245.171:8761}/eureka
    registerWithEureka: true
    fetchRegistry: true
  server:
    enableSelfPreservation: true