server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: 172.31.87.243
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  