spring:
  profile: peer1

server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: 172.31.21.134
    prefer-ip-address: true
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://172.31.92.175:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    
    
--- 
spring:
  profile: peer2

server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: 172.31.92.175
    prefer-ip-address: true
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://172.31.21.134:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true