server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: ec2-52-71-106-186.compute-1.amazonaws.com
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  