import groovy.json.JsonSlurper
node {

    withMaven(maven:'maven-3.6.2') {

        stage('Checkout') {
            git url: 'https://github.com/banibrata07/sample-spring-microservices.git', credentialsId: 'github-banibrataaws', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        }
        stage('S3 transfer') {
            script {
             s3Upload consoleLogLevel: 'INFO', dontWaitForConcurrentBuildCompletion: false, entries: [[bucket: 'aws-s3artifact-bani/gateway', excludedFile: '', flatten: true, gzipFiles: false, keepForever: false, managedArtifacts: false, noUploadOnFailure: false, selectedRegion: 'us-east-1', showDirectlyInBrowser: false, sourceFile: '**/gateway-service/target/*.jar', storageClass: 'STANDARD', uploadFromSlave: false, useServerSideEncryption: false], [bucket: 'aws-s3artifact-bani/gateway', excludedFile: '', flatten: true, gzipFiles: false, keepForever: false, managedArtifacts: false, noUploadOnFailure: false, selectedRegion: 'us-east-1', showDirectlyInBrowser: false, sourceFile: '**/gateway-service/Dockerfile', storageClass: 'STANDARD', uploadFromSlave: false, useServerSideEncryption: false]], pluginFailureResultConstraint: 'FAILURE', profileName: 'aws-s3artifact-bani', userMetadata: []
            }
        }
         stage('restart Server') {
           def restResponse = 'aws ec2 describe-instances --region us-east-1 --filters Name=tag:Name,Values=GatewayServer --query Reservations[].Instances[].InstanceId --output json'
           def proc = restResponse.execute()
           proc.waitFor()              
           def output = proc.in.text
           def exitcode= proc.exitValue()
           def error = proc.err.text

           if (error) {
               println "Std Err: ${error}"
               println "Process exit code: ${exitcode}"
               return exitcode
           }
           def list = new JsonSlurper().parseText(output)
           list.each { 
           def instance = it
           def command =  'aws ec2 reboot-instances --instance-ids replace --region us-east-1'
           command = command.replaceAll('replace',instance)
           println "Rebooting instance Id + instance " + command
           proc = command.execute()
           proc.waitFor()              
           output = proc.in.text
           exitcode= proc.exitValue()
           error = proc.err.text

           if (error) {
               println "Std Err: ${error}"
               println "Process exit code: ${exitcode}"
               return exitcode
           }
           }
            
        }
        /*
         stage('SSH transfer') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               sourceFiles: "gateway-service/Dockerfile",
               removePrefix: "gateway-service",
               remoteDirectory: "//usr//gateway",
              ),
              sshTransfer(
               sourceFiles: "gateway-service/target/gateway-service.jar",
               removePrefix: "gateway-service/target/",
               remoteDirectory: "//usr//gateway",
              )
             ])
           ])
         }
        }
        stage('SSH remove Previous image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "docker stop gateway;docker rm -f gateway;docker image rm -f gateway;"
              )
             ])
           ])
         }
        }
        stage('build image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "cd /usr/gateway;docker build -t gateway ."
              )
             ])
           ])
         }
        }
        stage('Run image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "docker run -d --network=host --name gateway -p 8765:8765 gateway;"
              )
             ])
           ])
         }
        }*/
        
    

}