node {

    withMaven(maven:'maven-3.6.2') {

        stage('Checkout') {
            git url: 'https://github.com/banibrata07/sample-spring-microservices.git', credentialsId: 'github-banibrataaws', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        
         stage('SSH transfer') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               sourceFiles: "gateway-service/Dockerfile",
               removePrefix: "gateway-service",
               remoteDirectory: "//usr//gateway",
              ),
              sshTransfer(
               sourceFiles: "gateway-service/target/gateway-service.jar",
               removePrefix: "gateway-service/target/",
               remoteDirectory: "//usr//gateway",
              )
             ])
           ])
         }
        }
        stage('SSH remove Previous image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "docker stop gateway;docker rm -f gateway;docker image rm -f gateway;"
              )
             ])
           ])
         }
        }
        stage('build image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "cd /usr/gateway;docker build -t gateway ."
              )
             ])
           ])
         }
        }
        stage('Run image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_gateway",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "docker run -d --network=host --name gateway -p 8765:8765 gateway;"
              )
             ])
           ])
         }
        }
        
    }

}