node {

    withMaven(maven:'maven-3.6.2') {

        stage('Checkout') {
            git url: 'https://github.com/banibrata07/sample-spring-microservices.git', credentialsId: 'github-banibrataaws', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        
        stage('S3 transfer') {
            script {
             s3Upload consoleLogLevel: 'INFO', dontWaitForConcurrentBuildCompletion: false, entries: [[bucket: 'aws-s3artifact-bani/customer', excludedFile: '', flatten: true, gzipFiles: false, keepForever: false, managedArtifacts: false, noUploadOnFailure: false, selectedRegion: 'us-east-1', showDirectlyInBrowser: false, sourceFile: '**/customer-service/target/*.jar', storageClass: 'STANDARD', uploadFromSlave: false, useServerSideEncryption: false], [bucket: 'aws-s3artifact-bani/customer', excludedFile: '', flatten: true, gzipFiles: false, keepForever: false, managedArtifacts: false, noUploadOnFailure: false, selectedRegion: 'us-east-1', showDirectlyInBrowser: false, sourceFile: '**/customer-service/Dockerfile', storageClass: 'STANDARD', uploadFromSlave: false, useServerSideEncryption: false]], pluginFailureResultConstraint: 'FAILURE', profileName: 'aws-s3artifact-bani', userMetadata: []
            }
        }
        }
          stage('Autoscaling Scale Out Instance Deployment') {
           def restResponse = 'aws autoscaling update-auto-scaling-group --auto-scaling-group-name appServerASG --min-size 2 --max-size 4 --desired-capacity 4  --health-check-grace-period 0 --default-cooldown 0 --region us-east-1'
           def proc = restResponse.execute()
           proc.waitFor()              
           def output = proc.in.text
           def exitcode= proc.exitValue()
           def error = proc.err.text

           if (error) {
               println "Std Err: ${error}"
               println "Process exit code: ${exitcode}"
               return exitcode
           }
           echo 'success from Autoscaling Scale Out Instance Deployment'
        }
        
        stage('Sleeping'){
         sleep 120
         echo 'waiting 120 sec'
        }

        
       
         stage('Autoscaling Scale In Instance Deployment') {
           def restResponse = 'aws autoscaling update-auto-scaling-group --auto-scaling-group-name appServerASG --min-size 2 --max-size 4 --desired-capacity 2  --health-check-grace-period 30 --default-cooldown 120 --region us-east-1'
           def proc = restResponse.execute()
           proc.waitFor()              
           def output = proc.in.text
           def exitcode= proc.exitValue()
           def error = proc.err.text

           if (error) {
               println "Std Err: ${error}"
               println "Process exit code: ${exitcode}"
               return exitcode
           }
            echo 'success from Autoscaling Scale In Instance Deployment'
        }
       
        stage('Wait Time Server restart'){
         sleep 120
         echo 'waiting 120 sec'
        }
        
        /* stage('SSH transfer') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_app",
             verbose: true,
             transfers: [
              sshTransfer(
               sourceFiles: "customer-service/Dockerfile",
               removePrefix: "customer-service",
               remoteDirectory: "//usr//customer",
              ),
              sshTransfer(
               sourceFiles: "customer-service/target/customer-service.jar",
               removePrefix: "customer-service/target/",
               remoteDirectory: "//usr//customer",
              )
             ])
           ])
         }
        }
        stage('SSH remove Previous image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_app",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "docker stop customer;docker rm -f customer;docker image rm -f customer;"
              )
             ])
           ])
         }
        }
        stage('build image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_app",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "cd /usr/customer;docker build -t customer ."
              )
             ])
           ])
         }
        }
        stage('Run image') {
         script {
          sshPublisher(
           continueOnError: false, failOnError: true,
           publishers: [
            sshPublisherDesc(
             configName: "docker_host_app",
             verbose: true,
             transfers: [
              sshTransfer(
               execCommand: "docker run -d --network=host --name customer -p 3333:3333 customer;"
              )
             ])
           ])
         }
        }*/
        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }  
    

}